### PR TITLE
Upgrade of the project in preparation of foundryvtt 0.8.0

### PR DESCRIPTION
**Pull request by p4535992**
The upgrade has the following features:
- Direct integration with easy target
- Direct integration with lib-targeting + minor bug fix
- Direct integration with better-target
- Converted to typescript project
- Minor and major bug fix
- Preparation to foundryvtt 0.8.0
- Partial integration with 'lib-wrapper'

There are still some minor bug or clean up of the code to made when i have time

### CODE REVIEW

**Comment by eadorin** [comment]
I would merge the PR but there is a conflict with target-enhancements.js

**Comment by p4535992** [comment]
Hi Eadorin happy to see you !!!
Forgive me I completely forgot I opened the pull request.
Unfortunately I have rewritten almost all the code and I don't think conflicts can be resolved except with "Stash" operations on your side.
Currently I have not solved any of the "serious" problems that your old version had (yes I have fixed a little bit here and there), but I am still in "Beta" as they say.
In particular I am banging my head on the error [Switching Scenes or Deleting tokens while target locks up game](https://github.com/eadorin/target-enhancements/issues/31) until I solve it the pull request makes no sense to be accepted.
If it doesn't bother you, I'd like to leave it open, because someone contacts me seeing the pull request still open.

**Comment by eadorin** [comment]
> Switching Scenes or Deleting tokens while target locks up game

I couldn't find the DisplayObject.ts file mentioned in your code base or I'd offer a suggestion there.

It looks like your rewrite is a great addition. Are you using the new libs that I had started to build out but hadn't finished? Keeping a table of target objects seemed like the most efficient way of tracking/listening to events.

**Comment by p4535992** [comment]
The "DisplayObejct" class is not mine is from the PIXI library "PIXI.DisplayObject", but the error is generated by the code with which the project builds the PIXI.Graphic of the target. In fact, the error does not appear if you click on the "Release all targets" button before making the player change scene.
To answer your first question, I too had thought of a table to manage the targets specifically I had thought of the "flags" mechanism that I had already seen on the module [MountUp](https://github.com/p4535992/MountUp/) so for each token we can have a array of PIXI.Graphics, but i haven't think to use your target library (still trying to learn XD), i have a [note on the README file](https://github.com/p4535992/target-enhancements#note), where after making everything work I was hoping to update that library as well. 
I will try to take a closer look at your library to see if I can use it for the suggested purpose
See you soon

**Comment by p4535992** [comment]
Seeing better the "lib-targeting" library I would say that it could be the ideal solution I try to integrate it these days.

**Comment by p4535992** [comment]
Nothing I have miserably failed in integrating the ["lib-target"](https://github.com/p4535992/target-enhancements/tree/master/src/module/lib-targeting) library that I had put into the project. 
I found that the problems related to the PIXI library were due to the "pulse" and "rotate" options for now I have commented them to go on. 
If you want to take the project back in your hand I had also prepared a bounty on the [Bounty on trelllo](https://trello.com/c/KvEZVMtw/213-modulebountyrevive-target-enhancements). 
For now I'll try to look for the other bugs, but by now I understand that I still lack the knowledge.

**Comment by eadorin** [comment]
we may be able to work on it together? You've integrated other works and I
don't want to see that effort wasted

**Comment by p4535992** [comment]
I would be really happy, but I am a "typescript" guy I don't want to force you to study something new, if it suits you better I can bring the project back in javascript. Let me know.

**Comment by eadorin** [comment]
I've done some typescript. Not an issue for me to roll with it moving
forward.

**Comment by p4535992** [comment]
Perfect then I close this PR, I reset the project on my side so that you can do the pull on your side without conflicts.
For now I will not touch anything about the current project, but over the weekend I wanted to try to integrate this project to add the graphics in the targets [Custom-Token-Animat](https://github.com/kandashi/Custom-Token-Animations). Let me know if I can help you in any other way.

**Pull request closed without merging**
